# -*- coding: utf-8 -*-
"""aaml_Homework_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycoDUCflqNasn5yCg-FzCoSswmiAji6P

6 points) For this problem, you will...
- Simulate a two-class classification with class imbalance based on two input featuresand 10k observations, where the class of “1” is only 1% of the whole data, as shown in class.

- Create your own KNearestNeighbors function based on the Usearch library

- Compare the performance of the KNN model created with cross-validation tuning for the optimal number of neighbors and the different methods for compensating the class imbalance, such as SMOTE (synthetic minority oversampling), ADASYN (adaptive synthetic minority oversampling), and FastKDE sampling.



(4 points) Provide a title, a reference to the data set, an abstract, and the main goal for the capstone project.
"""

pip install usearch

import usearch
print(usearch.__version__)

from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import ADASYN
import numpy as np
import usearch
import pandas as pd
from scipy.stats import mode
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.utils import resample
from sklearn.datasets import make_classification
from sklearn.metrics import classification_report as CR
import warnings
warnings.simplefilter(action='ignore')
from usearch.index import Index, MetricKind, search
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score, StratifiedKFold

"""To start, I will generate random data, making sure the class of 1 is only 1 percent of the whole data. This is class imbalance."""

X, y = make_classification(n_samples=10000, n_features=2, n_redundant=0,
	n_clusters_per_class=1, weights=[0.99], flip_y=0, random_state=42)

"""Now I will create my own KNN function based on Usearch, and then I will proceed with creating the cross-validation tuning function. But first...

Now I will display...
## SMOTE (synthetic minority oversampling) and ADASYN (adaptive synthetic minority oversampling)
"""

counter = Counter(y)
print(counter)

for label, _ in counter.items():
	row_ix = np.where(y == label)[0]
	plt.scatter(X[row_ix, 0], X[row_ix, 1], label=str(label),alpha=0.6,s=30)
plt.legend()
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from imblearn.over_sampling import SMOTE, ADASYN
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt
from usearch.index import Index, MetricKind, search
from sklearn.metrics import make_scorer, mean_squared_error
from sklearn.metrics import mean_squared_error as mse
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

#PLOTTING SMOTE



oversample = SMOTE()
Xsmote, ysmote = oversample.fit_resample(X, y)
# summarize the new class distribution

# scatter plot of examples by class label
for label, _ in counter.items():
	row_ix = np.where(ysmote == label)[0]
	plt.scatter(Xsmote[row_ix, 0], Xsmote[row_ix, 1], label=str(label),alpha=0.4)
plt.legend()
plt.show()

Xsmote

ysmote

"""KNN"""

scale = StandardScaler()
X_scaled = scale.fit_transform(X)
Xsmote_scaled = scale.fit_transform(Xsmote)
x_train, x_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.20, random_state = 42)
Xsmote_train, Xsmote_test, ysmote_train, ysmote_test = train_test_split(Xsmote_scaled, ysmote, test_size=0.20, random_state = 42)

!pip install usearch

import usearch

from scipy.spatial import cKDTree
import numpy as np

class KNearestNeighborsClassifier:
    def __init__(self, k=3):
        self.k = k
        self.train_data = None
        self.train_labels = None
        self.kdtree = None

    def fit(self, train_data, train_labels):
        self.train_data = train_data
        self.train_labels = train_labels
        self.kdtree = cKDTree(train_data)

    def predict(self, test_data):
        predictions = []
        for item in test_data:
            _, neighbor_indices = self.kdtree.query(item, k=self.k)
            pred_label = np.mean(self.train_labels[neighbor_indices])
            predictions.append(round(pred_label))
        return predictions

"""Now I want to perform k fold cross validation to find the best k value that produces the lowest mse. First up is the regular dataset:"""

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsClassifier

def find_best_k(x_train, y_train, x_test, y_test, k_values):
    best_k = None
    best_mse = float('inf')
    best_y_pred_test = None

    for k in k_values:
        mses = []
        kf = KFold(n_splits=5, shuffle=True, random_state=42)

        for train_index, val_index in kf.split(x_train):
            x_train_fold, x_val_fold = x_train[train_index], x_train[val_index]
            y_train_fold, y_val_fold = y_train[train_index], y_train[val_index]

            knn = KNeighborsClassifier(n_neighbors=k)
            knn.fit(x_train_fold, y_train_fold)
            y_pred = knn.predict(x_val_fold)
            mse_fold = mean_squared_error(y_val_fold, y_pred)
            mses.append(mse_fold)

        avg_mse = np.mean(mses)
        if avg_mse < best_mse:
            best_mse = avg_mse
            best_k = k

    # Train with the best k on the entire training set
    best_knn = KNeighborsClassifier(n_neighbors=best_k)
    best_knn.fit(x_train, y_train)
    best_y_pred_test = best_knn.predict(x_test)
    test_mse = mean_squared_error(y_test, best_y_pred_test)

    return best_k, test_mse, best_y_pred_test

# Example usage
k_values = range(1, 20)
best_k_reg, test_mse_reg, y_pred_test_reg = find_best_k(xkde_train, ykde_train, xkde_test, ykde_test, k_values)
print("Best k found:", best_k_reg)
print("MSE:", test_mse_reg)
print("Best y_pred_test:", y_pred_test_reg)

"""Now, I will provide the SMOTE dataset best k value:"""

def find_best_k(x_train, y_train, x_test, y_test, k_values):
    best_k = None
    best_mse = float('inf')

    for k in k_values:
        mses = []
        kf = KFold(n_splits=5, shuffle=True, random_state=42)

        for train_index, val_index in kf.split(x_train):
            x_train_fold, x_val_fold = x_train[train_index], x_train[val_index]
            y_train_fold, y_val_fold = y_train[train_index], y_train[val_index]

            knn = KNeighborsClassifier(n_neighbors=k)
            knn.fit(x_train_fold, y_train_fold)
            y_pred = knn.predict(x_val_fold)
            mse_fold = mean_squared_error(y_val_fold, y_pred)
            mses.append(mse_fold)

        avg_mse = np.mean(mses)
        if avg_mse < best_mse:
            best_mse = avg_mse
            best_k = k

    # Train with the best k on the entire training set
    best_knn = KNeighborsClassifier(n_neighbors=best_k)
    best_knn.fit(x_train, y_train)
    y_pred_test = best_knn.predict(x_test)
    test_mse = mean_squared_error(y_test, y_pred_test)

    return best_k, test_mse

# Example usage
k_values = range(1, 20)
best_k, test_mse = find_best_k(Xsmote_train, ysmote_train, Xsmote_test, ysmote_test, k_values)
print("Best k found:", best_k)
print("MSE:", test_mse)

#NOW I NEED TO PLOT ADASYN!

ada = ADASYN(random_state=42)
XADASYN, YADASYN = ada.fit_resample(X, y)
# scatter plot of examples by class label
for label, _ in counter.items():
	row_ix = np.where(YADASYN == label)[0]
	plt.scatter(XADASYN[row_ix, 0], XADASYN[row_ix, 1], label=str(label),alpha=0.4)
plt.legend()
plt.show()

from sklearn.model_selection import KFold, train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

# Scaling Adasyn data
scale = StandardScaler()
XADASYN_SCALED = scale.fit_transform(XADASYN)
xadasyn_train, xadasyn_test, yadasyn_train, yadasyn_test = train_test_split(XADASYN_SCALED, YADASYN, test_size=0.20, random_state=42)

def find_best_k(x_train, y_train, x_test, y_test, k_values):
    best_k = None
    best_mse = float('inf')

    for k in k_values:
        mses = []
        kf = KFold(n_splits=5, shuffle=True, random_state=42)

        for train_index, val_index in kf.split(x_train):
            x_train_fold, x_val_fold = x_train[train_index], x_train[val_index]
            y_train_fold, y_val_fold = y_train[train_index], y_train[val_index]

            knn = KNeighborsClassifier(n_neighbors=k)
            knn.fit(x_train_fold, y_train_fold)
            y_pred = knn.predict(x_val_fold)
            mse_fold = mean_squared_error(y_val_fold, y_pred)
            mses.append(mse_fold)

        avg_mse = np.mean(mses)
        if avg_mse < best_mse:
            best_mse = avg_mse
            best_k = k

    # Train with the best k on the entire training set
    best_knn = KNeighborsClassifier(n_neighbors=best_k)
    best_knn.fit(x_train, y_train)
    y_pred_test = best_knn.predict(x_test)
    test_mse = mean_squared_error(y_test, y_pred_test)

    return best_k, test_mse

# Example usage
k_values = range(1, 20)
best_k, test_mse = find_best_k(xadasyn_train, yadasyn_train, xadasyn_test, yadasyn_test, k_values)
print("Best k found:", best_k)
print("MSE:", test_mse)

"""Now, I will be working with KDE!"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from fastkde import fastKDE

# Generate a classification dataset
X, y = make_classification(n_samples=10000, n_features=2, n_redundant=0,
	n_clusters_per_class=1, weights=[0.99], flip_y=0, random_state=42)

# Extract features
x1, x2 = X[:, 0], X[:, 1]

# Create the KDE object and compute the PDF
myPDF = fastKDE.pdf(x1, x2, num_points=513, var_names=['x1', 'x2'])

# Plot the PDF
myPDF.plot()
plt.show()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
x_train, x_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.20, random_state=42)

def find_best_k(x_train, y_train, x_test, y_test, k_values):
    best_k = None
    best_mse = float('inf')

    for k in k_values:
        mses = []
        kf = KFold(n_splits=5, shuffle=True, random_state=42)

        for train_index, val_index in kf.split(x_train):
            x_train_fold, x_val_fold = x_train[train_index], x_train[val_index]
            y_train_fold, y_val_fold = y_train[train_index], y_train[val_index]

            knn = KNeighborsClassifier(n_neighbors=k)
            knn.fit(x_train_fold, y_train_fold)
            y_pred = knn.predict(x_val_fold)
            mse_fold = mean_squared_error(y_val_fold, y_pred)
            mses.append(mse_fold)

        avg_mse = np.mean(mses)
        if avg_mse < best_mse:
            best_mse = avg_mse
            best_k = k

    # Train with the best k on the entire training set
    best_knn = KNeighborsClassifier(n_neighbors=best_k)
    best_knn.fit(x_train, y_train)
    y_pred_test = best_knn.predict(x_test)
    test_mse = mean_squared_error(y_test, y_pred_test)

    return best_k, test_mse

# Example usage
k_values = range(1, 20)
best_k, test_mse = find_best_k(x_train, y_train, x_test, y_test, k_values)
print("Best k found:", best_k)
print("MSE:", test_mse)

















from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

scale = StandardScaler()
X_scaled = scale.fit_transform(X)
Xsmote_scaled = scale.fit_transform(Xsmote)
x_train, x_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.20, random_state = 42)
Xsmote_train, Xsmote_test, ysmote_train, ysmote_test = train_test_split(Xsmote_scaled, ysmote, test_size=0.20, random_state = 42)


def find_best_k(x_train, y_train, x_test, y_test, k_values):
    best_k = None
    best_mse = float('inf')

    for k in k_values:
        mses = []
        kf = KFold(n_splits=5, shuffle=True, random_state=42)

        for train_index, val_index in kf.split(x_train):
            x_train_fold, x_val_fold = x_train[train_index], x_train[val_index]
            y_train_fold, y_val_fold = y_train[train_index], y_train[val_index]

            knn = KNearestNeighborsClassifier(k=k)
            knn.fit(x_train_fold, y_train_fold)
            y_pred = knn.predict(x_val_fold)
            mse_fold = mean_squared_error(y_val_fold, y_pred)
            mses.append(mse_fold)

        avg_mse = np.mean(mses)
        if avg_mse < best_mse:
            best_mse = avg_mse
            best_k = k

    # Train with the best k on the entire training set
    best_knn = KNearestNeighborsClassifier(k=best_k)
    best_knn.fit(x_train, y_train)
    y_pred_test = best_knn.predict(x_test)
    test_mse = mean_squared_error(y_test, y_pred_test)

    return best_k, test_mse

# Example usage
k_values = range(1, 20)
best_k, test_mse = find_best_k(Xsmote_train, Xsmote_test, ysmote_train, ysmote_test, k_values)
print("Best k found:", best_k)
print("MSE:", test_mse)

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

def find_best_k(x_train, y_train, x_test, y_test, k_values):
    best_k = None
    best_mse = float('inf')

    for k in k_values:
        mses = []
        kf = KFold(n_splits=5, shuffle=True, random_state=42) # Set shuffle to True

        for train_index, val_index in kf.split(x_train):
            x_train_fold, x_val_fold = x_train[train_index], x_train[val_index]
            # Ensure that the training data and labels have the same size
            assert len(x_train_fold) == len(y_train[train

"""# KDE"""

!pip install -q fastKDE

!pip install fastKDE

#! pip install --upgrade -q statsmodels
import statsmodels.api as sm

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
# %config InlineBackend.figure_format = 'retina'
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 150
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import numpy as np
import fastkde
import statsmodels.api as sm
from sklearn.neighbors import KernelDensity

#Generate two random variables dataset (representing 100000 pairs of datapoints)
N1 = np.random.normal(size=1000)
N2 = np.random.normal(scale=0.5, size=1000)
x = N1+N2
y = N1-N2

print(len(x))

print(len(y))

y

#Generate two random variables dataset (representing 100000 pairs of datapoints)
N1 = np.random.normal(size=1000)
N2 = np.random.normal(scale=0.5, size=1000)
x = N1+N2
y = N1-N2

myPDF = fastkde.pdf(x,y,num_points=513,var_names=['x','y'])
myPDF.plot()
plt.show()

from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt
from fastkde import fastKDE

X, y = make_classification(n_samples=10000, n_features=2, n_informative=2, n_redundant=0,
                           n_clusters_per_class=1, weights=[0.99], flip_y=0, random_state=42)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

minority_mask = (y == 1)
majority_mask = ~minority_mask

X_minority = X_scaled[minority_mask]
X_majority = X_scaled[majority_mask]

# Estimate the KDE PDF for the minority class
x_minority, y_minority = X_minority[:, 0], X_minority[:, 1]
pdf_minority = fastKDE.pdf(x_minority, y_minority, num_points=513, var_names=['x', 'y'])

# Create a mesh grid to evaluate the PDF
x_mesh = np.linspace(min(x_minority), max(x_minority), 513)
y_mesh = np.linspace(min(y_minority), max(y_minority), 513)
xx, yy = np.meshgrid(x_mesh, y_mesh)
pdf_values = pdf_minority.values.T

# Flatten the mesh grid and PDF values for sampling
points_grid = np.column_stack([xx.ravel(), yy.ravel()])
pdf_flat = pdf_values.ravel()

# Normalize the PDF values to obtain a probability distribution
pdf_flat /= pdf_flat.sum()

# Number of samples required
num_samples_minority = 9900

# Draw new samples using rejection sampling
sample_indices = np.random.choice(len(pdf_flat), size=num_samples_minority, p=pdf_flat)
X_sampled_minority = points_grid[sample_indices]

# Combine the original and sampled datasets
X_combined = np.row_stack([X_majority, X_minority, X_sampled_minority])
y_combined = np.concatenate([np.zeros(len(X_majority)), np.ones(len(X_minority) + len(X_sampled_minority))])

# Summarize the new class distribution
counter = Counter(y_combined)
print(counter)

# Scatter plot of examples by class label
for label, _ in counter.items():
    row_ix = np.where(y_combined == label)[0]
    plt.scatter(X_combined[row_ix, 0], X_combined[row_ix, 1], label=str(label), alpha=0.4)

plt.legend()
plt.xlabel('x')
plt.ylabel('y')
plt.title('KDE')
plt.show()

Xkde_scaled

y_combined

Xkde_scaled = scale.fit_transform(X_combined)
xkde_train, xkde_test, ykde_train, ykde_test = train_test_split(Xkde_scaled, y_combined, test_size=0.20, random_state = 42)
xkde_train, xkde_test, ykde_train, ykde_test = train_test_split(Xkde_scaled, y_combined, test_size=0.20, random_state=42)

def find_best_k(x_train, y_train, x_test, y_test, k_values):
    best_k = None
    best_mse = float('inf')

    for k in k_values:
        mses = []
        kf = KFold(n_splits=5, shuffle=True, random_state=42)

        for train_index, val_index in kf.split(x_train):
            x_train_fold, x_val_fold = x_train[train_index], x_train[val_index]
            y_train_fold, y_val_fold = y_train[train_index], y_train[val_index]

            knn = KNeighborsClassifier(n_neighbors=k)
            knn.fit(x_train_fold, y_train_fold)
            y_pred = knn.predict(x_val_fold)
            mse_fold = mean_squared_error(y_val_fold, y_pred)
            mses.append(mse_fold)

        avg_mse = np.mean(mses)
        if avg_mse < best_mse:
            best_mse = avg_mse
            best_k = k

    # Train with the best k on the entire training set
    best_knn = KNeighborsClassifier(n_neighbors=best_k)
    best_knn.fit(x_train, y_train)
    y_pred_test = best_knn.predict(x_test)
    test_mse = mean_squared_error(y_test, y_pred_test)

    return best_k, test_mse

# Example usage
k_values = range(1, 20)
best_k, test_mse = find_best_k(xkde_train, ykde_train, xkde_test, ykde_test, k_values)
print("Best k found:", best_k)
print("MSE:", test_mse)

"""# My Capstone Project

(4 points) Provide a title, a reference to the data set, an abstract, and the main goal for the capstone project.

# Title: Pokémon Battle Prediction!
Reference to dataset: https://www.kaggle.com/datasets/lantian773030/pokemonclassification/code?datasetId=410745&sortBy=voteCount
Abstract:

Have an image of a Pokémon in your head but can’t remember the name? Fascinated by the wide variety of Pokémon but overwhelmed by how to handle them all? Curious about how your favorite Pokémon would perform in battle? I aim to work on a final project that will:

1. Predict the names of two Pokémon based on a given image and...
2. Predict which of these two Pokémon would win in a battle based on game statistics.

By integrating these models, the project aims to deliver an interactive tool for Pokémon enthusiasts and trainers alike, offering an intuitive way to identify Pokémon from text and images. This makes it accessible not only to experts but also to amateurs like me, who simply enjoy fun and cool-looking Pokémon, while also providing predictive insights into potential battle outcomes based on game statistics!

Ultimately, Pokémon Battle Prediction seeks to enrich the Pokémon gaming experience by simplifying Pokémon identification and enhancing strategic planning for battles.
"""

